version: '3'

services:
df
  reverse-proxy:


mj

weather-report:


temperature-service:


precip_service:
 
this i sthe another actaull thing which is the kind of jhbiudyviy
hi this the first project which i have forkrd